server:
  port: 8080

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      default-filters:
        -TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
            - id: microservice-user
              uri: lb://microservice-user
              predicates:
                - Path=/users/**, /reservations/**
              filters:
                  - RemoveRequestHeader=Cookie
            - id: microservice-hotel
              uri: lb://microservice-hotel
              predicates:
                - Path=/hotels/**, /rooms/**
            - id: microservice-opinions
              uri: lb://microservice-opinions
              predicates:
                - Path=/opinions/**
  security:
    oauth2:
      client:
        provider:
          keycloak:
              authorization-uri: http://localhost:8180/realms/master/protocol/openid-connect/auth
              user-info-uri: http://localhost:8180/realms/master/protocol/openid-connect/userinfo
              user-name-attribute: preferred_username
              token-uri: http://localhost:8180/realms/master/protocol/openid-connect/token
        registration:
            client:
              provider: keycloak
              client-id: client
              client-secret: PEiUmDVgIPB6aidpG5ZHek1ybIVw4TMB
              authorization-grant-type: authorization_code
              redirect-uri: http://localhost:8080/login/oauth2/code/client