spring:
  application:
    name: microservice-user
  config:
    import: "optional:configserver:http://localhost:8081"  //puerto del servidor de configuración (revisar en el microservicio de configuración)
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
