spring:
  application:
    name: microservice-user
  config:
    import: "optional:configserver:http://localhost:8081"
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

feign:
  client:
    config:
      default:  # Aplica a todos los clientes Feign
        connectTimeout: 2000    # Tiempo máximo para establecer conexión (2 segundos)
        readTimeout: 2000       # Tiempo máximo de espera de respuesta (2 segundos)
        loggerLevel: basic      # Nivel de logging (muestra método HTTP, URL y código de respuesta)