server:
    port: 8081

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/NicolasPerezU/microservices-hotel
          search-paths: config-data
          default-label: circuit-breaker
  profiles:
    active: git

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost